admin_web_city_index:
  path: /admin/city
  methods: [ GET ]
  controller: App\UI\Web\Controller\CityManagement\CityManagementController::index

admin_web_city_show:
  path: /admin/city/show/{id<\d+>}
  methods: [ GET ]
  controller: App\UI\Web\Controller\CityManagement\CityManagementController::show

admin_web_city_create:
  path: /admin/city/create
  methods: [ GET, POST ]
  controller: App\UI\Web\Controller\CityManagement\CityManagementController::create

admin_web_city_update:
  path: /admin/city/update/{id<\d+>}
  methods: [ GET, POST ]
  controller: App\UI\Web\Controller\CityManagement\CityManagementController::update

