resources:
  App\Domain\Entity\City:
    shortName: 'City'
    description: 'City where sensors are mounted'
    operations:
      ApiPlatform\Metadata\GetCollection:
        name: 'api_cities_get'
        method: GET
        options:
          expose: true
      ApiPlatform\Metadata\Get:
        name: 'api_city_get'
        method: GET
        options:
          expose: true
      ApiPlatform\Metadata\Delete:
        name: 'api_city_delete'
        method: DELETE
        options:
          expose: true
        security: 'is_granted("ROLE_ADMIN")'

properties:
  App\Domain\Entity\City:
    name:
      description: 'Measured value of Particulate Matter PM10'
    positionX:
      description: 'Horizontal position on the map'
    positionY:
      description: 'Vertical position on the map'
