
resources:
  App\Domain\Entity\Measurement:
    shortName: 'Measurement'
    description: 'Sensor readings'
    operations:
      ApiPlatform\Metadata\GetCollection:
        name: 'api_measurements_get'
        method: GET
        filters: [ 'measurements.search_filter', 'measurements.date_filter' ]
        options:
          expose: true
      ApiPlatform\Metadata\Get:
        name: 'api_measurement_get'
        method: GET
      ApiPlatform\Metadata\Post:
        name: 'api_measurements_post'
        method: POST

properties:
  App\Domain\Entity\Measurement:
    pm10:
      description: 'Measured value of Particulate Matter PM10'
    pm25:
      description: 'Measured value of Particulate Matter PM2.5'
    sensor:
      description: 'Measurement sensor'
