resources:
  App\Domain\Entity\Sensor:
    shortName: 'Sensor'
    description: 'Sensors mounted in specific places'
    normalizationContext:
      groups: [ 'sensor.read' ]
    operations:
      ApiPlatform\Metadata\GetCollection:
        name: 'api_sensors_get'
        method: GET
        filters: [ 'sensors.search_filter' ]
        options:
          expose: true
      ApiPlatform\Metadata\Get:
        name: 'api_sensor_get'
        method: GET
        options:
          expose: true
      ApiPlatform\Metadata\Delete:
        name: 'api_sensor_delete'
        method: DELETE
        options:
          expose: true
        security: 'is_granted("ROLE_ADMIN")'

properties:
  App\Domain\Entity\Sensor:
    name:
      description: 'The name of the Sensor'
    city:
      description: 'The city of the Sensor'
    address:
      description: 'The address of the Sensor'
    measurements:
      description: 'The measurements collection of the Sensor'
