resources:
  App\Domain\Entity\City:
    shortName: 'City'
    description: 'City where sensors are mounted'
  App\Domain\Entity\Sensor:
    shortName: 'Sensor'
    description: 'Sensors mounted in specific places'
  App\Domain\Entity\Measurement:
    shortName: 'Measurement'
    description: 'Sensor readings'
