api_measurements_weekly_get:
  path: /api/sensor-measurements/weekly
  methods: [ GET ]
  controller: App\UI\Controller\Api\Measurement\MeasurementController::weeklyGet
  options:
    expose: true

api_measurements_monthly_get:
  path: /api/sensor-measurements/monthly
  methods: [ GET ]
  controller: App\UI\Controller\Api\Measurement\MeasurementController::monthlyGet
  options:
    expose: true
